# Generated by Django 5.2.11 on 2026-02-24 12:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('IRR', 'Iranian Rial')], max_length=10)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('TRANSFER', 'Transfer')], max_length=10)),
                ('status', models.CharField(default='COMPLETED', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('wallet_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_from', to='wallet.wallet')),
                ('wallet_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_to', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['wallet_from'], name='transaction_wallet__83cf52_idx'), models.Index(fields=['wallet_to'], name='transaction_wallet__009425_idx'), models.Index(fields=['currency'], name='transaction_currenc_e0f8b1_idx'), models.Index(fields=['idempotency_key'], name='transaction_idempot_776dfc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.0000'))), name='transaction_amount_positive')],
            },
        ),
    ]
